FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY run_1b.py .
COPY challenge1b_input.json .
COPY pdfs ./pdfs
COPY 1a_outputs ./1a_outputs

CMD ["python", "run_1b.py"]
